version: '3.8'
services:
  api:
    build:
      context: .
      target: development
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dbname
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      PORT: 3000
      NODE_ENV: development
    ports:
      - 3000:3000
    depends_on:
      - db
    networks:
      - api-network
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dbname
    # volumes:
    #   - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - api-network
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - 80:80
    depends_on:
      - api
    networks:
      - api-network
networks:
  api-network:
    driver: bridge
# volumes:
#   db-data:
