version: '3.8'
services:
  app:
    container_name: app
    build: .
    restart: always
    ports:
      - 3000:3000
    # environment:
    #   NODE_ENV: production
    #   POSTGRES_HOST: db
    #   POSTGRES_PORT: 5432
    #   POSTGRES_USER: postgres
    #   POSTGRES_PASSWORD: postgres
    #   POSTGRES_DB: db
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:14.3
    restart: always
    environment:
      POSTGRES_USER: jose
      POSTGRES_PASSWORD: pswEntradasATuAlcance
      POSTGRES_DB: EntradasATuAlcance
    ports:
      - 5432:5432
  nginx:
    container_name: nginx
    image: nginx:latest
    restart: always
    ports:
      - 80:80
      # - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      # - ./certs:/etc/nginx/certs
    depends_on:
      - app
