version: '3.8'
services:
  env_file:
   - ./.env
  environment:
  - BACKEND_NODE_PORT=${BACKEND_NODE_PORT}        
  - BACKEND_NGINX_PORT=${BACKEND_NGINX_PORT}
  - BACKEND_POSTGRES_PORT=${BACKEND_POSTGRES_PORT}    
  - DB_HOST=${DB_HOST}  
  - DB_NAME=${DB_NAME}  
  - DB_USERNAME=${DB_USERNAME}  
  - DB_PASSWORD=${DB_PASSWORD}  
  - DB_PORT=${DB_PORT}  
  - PORT=${PORT}  
  - HOST_API=${HOST_API}  
  - JWT_SECRET=${JWT_SECRET} 
  - NODE_ENV=${NODE_ENV} 
  api:
    build: .
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}  
      POSTGRES_HOST: ${DB_HOST}
      POSTGRES_PORT: ${BACKEND_POSTGRES_PORT}
      NODE_ENV: ${NODE_ENV}
    ports:
      - ${BACKEND_NODE_PORT}:3000
    depends_on:
      - db
  db:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${BACKEND_POSTGRES_PORT}:5432
  nginx:
    image: nginx:alpine
    ports:
      - ${BACKEND_NGINX_PORT}:80
    depends_on:
      - api
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
