version: '3'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/myapp
    depends_on:
      - db
    networks:
      - myapp-network

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: myapp
    # volumes:
    #   - myapp-data:/var/lib/postgresql/data/
    networks:
      - myapp-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    # volumes:
    #   - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    networks:
      - myapp-network

networks:
  myapp-network:
    driver: bridge

# volumes:
#   myapp-data:
