# Base image
FROM node:14-alpine

# Create app directory
WORKDIR /usr/src/app

# Install dependencies
COPY package*.json ./
RUN npm install

# Copy app source
COPY . .

# Expose port 3000
EXPOSE 3000

# Run the app
CMD ["npm", "run", "start:prod"]
